config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'plans#index'
  resources :plans do
    resources :likes, only: [:create, :destroy]
    collection do
      get 'men'
      get 'women'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :plan
  belongs_to :user
  validates_uniqueness_of :plan_id, scope: :user_id
end

app/models/meal.rb
class Meal < ActiveHash::Base
  self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '朝' },
   { id: 3, name: '昼' },
   { id: 4, name: '夜' }
]

include ActiveHash::Associations
  has_many :plans
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :meal
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :plan
    validates :date
  end
  validates :meal_id, numericality: { other_than: 1 } 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :plans, dependent: :destroy
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :nickname
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
  end

  def already_liked?(plan)
    self.likes.exists?(plan_id: plan.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(plan_id: params[:plan_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @plan = Plan.find(params[:plan_id])
    @like = current_user.likes.find_by(plan_id: @plan.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_plan, only: [:edit, :update, :destroy]

  def index
    get_week
    @plan = Plan.new
  end

  def create
    Plan.create(plan_params)
    redirect_to action: :index
  end

  def destroy
    @plan.destroy
    redirect_to user_path(current_user.id)
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def men
  end

  def women
  end

  private

  def plan_params
    params.require(:plan).permit(:date, :plan, :meal_id).merge(user_id: current_user.id)
  end

  def get_week
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
  
    @todays_date = Date.today
    @week_days = []

    plans = Plan.where(date: @todays_date..@todays_date + 6)
   
    7.times do |x|    
      today_plans = []
      plans.each do |plan|
        today_plans.push(plan.plan) if plan.date == @todays_date + x
      end
      today_meals = []
      plans.each do |plan|
        today_meals.push(plan.meal.name) if plan.date == @todays_date + x
      end


      wday_num = Date.today.wday + x
  
      if wday_num >= 7
        wday_num = wday_num -7
      end

      days = { month: (@todays_date + x).month, date: (@todays_date + x).day, plans: today_plans, meals: today_meals, wday: wdays[wday_num] }
      @week_days.push(days)
    end
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def ensure_correct_user
    unless @plan.user == current_user
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @plans = Plan.where(user_id: current_user.id)
    @plan = Plan.find_by(params[:plan_id])
    @like = Like.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eatcalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<div class="contents edit">
  <div class="plan_edit">
    <h3>編集する</h3>
    <%= form_with model: @plan, url: plan_path, class: 'form' do |f| %>
      <%= f.label :日付を選択, class: 'lavel' %>
      <%= f.date_field :date, class: 'date-select' %>
      <%= f.label :メニューを入力, class: 'lavel' %>
      <%= f.text_field :plan, class: 'text-input' , placeholder:'例 目玉焼き' %>
      <%= f.label :時間帯を入力, class: 'lavel' %>
      <%= f.collection_select(:meal_id, Meal.all, :id, :name, {}, {class:'meal-select', id:'meal'}) %>
      <%= f.submit '更新' %>
    <% end %>
  </div>
</div>

app/views/plans/index.html.erb
<header class='top-header' >
  <div page-header>
    <div class='header-title'>  
      <h1 class='page-title'>FOOD RECORD</h1>
      <P id='p1'>
      朝・昼・夜の食事メニューを入力し自分の食生活を見直してみよう！
      マイページから基礎代謝・BMIを計算！！
      </p>
    </div>
  </div>
  <div class='nav'>
    <ul class='header-lists'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: 'user-nickname' %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'logout' %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: 'login' %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: 'sign-up' %></li>
      <% end %>
    </ul>
  </ul>
</header>

<body>
  <%= form_with model: @plan, url: plans_path, class: 'form' do |f| %>
    <%= f.label :日付を選択, class: 'lavel' %>
    <%= f.date_field :date, class: 'date-select' %>
    <%= f.label :メニューを入力, class: 'lavel' %>
    <%= f.text_field :plan, class: 'text-input' %>
    <%= f.label :時間帯を入力, class: 'lavel' %>
    <%= f.collection_select(:meal_id, Meal.all, :id, :name, {}, {class:'meal-select', id:'meal'}) %>
    <%= f.submit '保存' %>
  <% end %>

  <div class='calendar'>
    <% @week_days.each do |day| %>
      <div class='item'>
        <div class='date'>
          <%= day[:month] %>/<%= day[:date] %><%= day[:wday] %>
        </div>
        <ul class='contents'>
          <ul class='meal_content'>
            <% day[:meals].each do |meal| %>
              <li class='meal-list'>・<%= meal %> </li>
            <% end %>
          </ul>
          <ul class='plan_content'>
            <% day[:plans].each do |plan| %>
              <li class='plan-list'><%= plan %> </li>
            <% end %>
          </ul>
        </ul>
      </div>
    <% end %>
  </div>
</body>

<footer>
  <div class='wrapper'>
    <P><small>&copy; 2021 96th team D</small></p>
  </div>
</footer>

app/views/plans/men.html.erb
<header class='userheader'>
  <div class='my_page'>
    <%= link_to 'トップページへ', root_path, id:'top_page' %>
  </div>
  <div class='nav'>
    <li><%= link_to 'マイページへ', user_path(current_user.id), id:'top_page' %></li>
  </div>
</header>

<body>
  <div class=bmi >
    <p class='caliculation'>身長</p>
    <input type='text' id='height' class="field"><br><br>
    <p class='caliculation'>体重</p>
    <input type='text' id='weight' class="field"><br><br>
    <button type='botton' id='btn' onclick="bmi()">
    <h2 class='text-input'>BMI=<b id='bmi_index'></b></h2>
  </div>

  <div class=calorie>
    <p class='caliculation'>年齢</p>
    <input type='text' id='age' class="field"><br><br>
    <button type='botton' id='btn' onclick="calorie()">
    <h3 class='text-input'>基礎代謝=<b id='calorie_index'></b></h3>
  </div>

 <script>
 function bmi() {
   const height = parseFloat(document.getElementById('height').value)
   const weight = parseFloat(document.getElementById('weight').value)
   const h = height / 100
   const bmi = weight/h/h;
   const userBMI = document.getElementById('bmi_index')
   userBMI.textContent = bmi.toFixed(2);
 };

 function calorie() {
   const height = parseFloat(document.getElementById('height').value)
   const weight = parseFloat(document.getElementById('weight').value)
   const age = parseFloat(document.getElementById('age').value)
   const calorie = 10 * weight + 6.25 * height - 5 * age + 5;
   const userCALORIE = document.getElementById('calorie_index')
   userCALORIE.textContent = calorie.toFixed(2);
 };
 </script>
</body>

app/views/plans/women.html.erb
<header class='userheader'>
  <div class='my_page'>
    <%= link_to 'トップページへ', root_path, id:'top_page' %>
  </div>
  <div class='nav'>
    <li><%= link_to 'マイページへ', user_path(current_user.id), id:'top_page' %></li>
  </div>
</header>

<body>

  <div class=bmi>
    身長<input type='text' id='height' ><br><br>
    体重<input type='text' id='weight' ><br><br>
    <button type='botton' onclick="bmi()">
    <h2 class='text-input'>BMI=<b id='bmi_index'></b></h2>
  </div>

  <div class=calorie>
    年齢<input type='text' id='age' ><br><br>
    <button type='botton' onclick="calorie()">
    <h3 class='text-input'>基礎代謝=<b id='calorie_index'></b></h3>
  </div>

  <script>
 function bmi() {
   const height = parseFloat(document.getElementById('height').value)
   const weight = parseFloat(document.getElementById('weight').value)
   const h = height / 100
   const bmi = weight/h/h;
   const userBMI = document.getElementById('bmi_index')
   userBMI.textContent = bmi.toFixed(2);
 };

 function calorie() {
   const height = parseFloat(document.getElementById('height').value)
   const weight = parseFloat(document.getElementById('weight').value)
   const age = parseFloat(document.getElementById('age').value)
   const calorie = 10 * weight + 6.25 * height - 5 * age - 161;
   const userCALORIE = document.getElementById('calorie_index')
   userCALORIE.textContent = calorie.toFixed(2);
 };
 </script>
</body>

app/views/users/show.html.erb
<header class='userheader'>
  <div class='top_page'>
    <%= link_to 'トップページへ', root_path, id:'top_page' %>
  </div>
  <div class='nav'>
    <li class='men'>
      <%= link_to '基礎代謝計算（男性）', men_plans_path, id:'pagecahnge', method: :get %>
    </li>
    <li class='women'>
      <%= link_to '基礎代謝計算（女性）', women_plans_path, id:'pagecahnge', method: :get %>
    </li>
  </div>
</header>

<div class='user_contents'>
  <p id='nickname'><%= @nickname %>さんの投稿一覧</p>
  <% @plans.each do |plan| %>
    <div class='content_post'>
      <p><%= plan.date %></p>
      <p><%= plan.meal.name %> <%= plan.plan %></p>
      <p>いいね件数: <%= plan.likes.count %></p>
      <h3 id='like'>
        <% if current_user.already_liked?(plan) %>
          <%= button_to 'いいねを取り消す', plan_like_path(plan), method: :delete %>
        <% else %>
          <%= button_to 'いいね', plan_likes_path(plan) %>
        <% end %>
      </h3>
    </div>
    <div class='edit'>
      <li><%= link_to '編集', edit_plan_path(plan), id:'edit', method: :get %></li>
      <li><%= link_to '削除', plan_path(plan.id), id:'edit', method: :delete %><li>
    </div>
  <% end %>
</div>